CREATE TABLE student_profiles (
    id               BIGINT AUTO_INCREMENT PRIMARY KEY,
    userId           BIGINT       NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    departmentId     BIGINT       NOT NULL REFERENCES departments(id),
    semesterId       BIGINT       NOT NULL REFERENCES semesters(id),
    name             VARCHAR(150) NOT NULL,
    regNo            VARCHAR(50)  NOT NULL UNIQUE,
    phone            VARCHAR(20),
    year             INT          NOT NULL,
    section          VARCHAR(5)   NOT NULL,
    isHosteler       BOOLEAN      NOT NULL DEFAULT FALSE,
    hostelType       VARCHAR(10)  DEFAULT NULL,
    roomNo           VARCHAR(20)  DEFAULT NULL,
    parentName       VARCHAR(150),
    parentPhone      VARCHAR(20),
    parentEmail      VARCHAR(150),
    address          TEXT,
    emergencyContact VARCHAR(20),
    profilePicPath   VARCHAR(255),
    mentorId         BIGINT       DEFAULT NULL REFERENCES faculty_profiles(id),
    classAdvisorId   BIGINT       DEFAULT NULL REFERENCES faculty_profiles(id),
    leaveBalance     INT          NOT NULL DEFAULT 20,
    createdAt        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_sp_dept       (departmentId),
    INDEX idx_sp_mentor     (mentorId),
    INDEX idx_sp_advisor    (classAdvisorId),
    INDEX idx_sp_year_sec   (departmentId, year, section),
    INDEX idx_sp_hostel     (isHosteler, hostelType)
);
