package com.permithub.entity;

public enum RequestStatus {
    PENDING,
    APPROVED_BY_MENTOR,
    APPROVED_BY_EVENT_COORDINATOR,
    APPROVED_BY_CLASS_ADVISOR,
    APPROVED_BY_HOD,
    APPROVED_BY_WARDEN,
    APPROVED_BY_AO,
    APPROVED_BY_PRINCIPAL,
    REJECTED_BY_MENTOR,
    REJECTED_BY_EVENT_COORDINATOR,
    REJECTED_BY_CLASS_ADVISOR,
    REJECTED_BY_HOD,
    REJECTED_BY_WARDEN,
    REJECTED_BY_AO,
    REJECTED_BY_PRINCIPAL,
    PARENT_PENDING,
    PARENT_APPROVED,
    PARENT_REJECTED,
    COMPLETED,
    EXPIRED,
    CANCELLED
}